# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelSwift

	platform :ios, '8.0'
	pod 'SDWebImage', '~> 5.0'
	pod 'Alamofire'
  pod 'NVActivityIndicatorView'

end
